### PR TITLE
SPACE-2777: Unify NOTICE extension

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-css-style-gate-PR52

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-gate/15/ : SUCCESS in 25s
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-fossa-scanning-zuul/6/ : SUCCESS in 35s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/23/ : SUCCESS in 12s

**Pull request merged**
