### PR TITLE
RELATED: SPACE-2092 Add NOTICE.txt to package.json files to be bundled to npm package

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-css-style-gate-PR43

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-gate/6/ : SUCCESS in 34s
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-fossa-scanning-zuul-el7/8/ : SUCCESS in 1m 30s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/14/ : SUCCESS in 21s

**Pull request merged**
