### PR TITLE
RELATED: SPACE-2092 Add NOTICE file and update license

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by ivan-nejezchleb — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-css-style-gate-PR42

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-gate/5/ : SUCCESS in 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-fossa-scanning-zuul-el7/7/ : SUCCESS in 1m 27s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/13/ : SUCCESS in 19s

**Pull request merged**
