### PR TITLE
RELATED: FET-564 Sonar config v2

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
extended check sonar

**Comment by ghost** [comment]
Build succeeded (check-extended pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
extended check sonar

**Comment by ghost** [comment]
Build succeeded (check-extended pipeline).

**Comment by ivanmjartan** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-css-style-check-extended-sonar-PR27

**Comment by ghost** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-el7/1/ : SUCCESS in 43s (non-voting)

**Comment by yenkins** [comment]
### Sonar scan result
 - No bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-css-style-gate-PR27

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-fossa-scanning-zuul-el7/2/ : SUCCESS in 2m 03s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-el7/2/ : SUCCESS in 34s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/8/ : SUCCESS in 19s

**Pull request merged**
