### PR TITLE
RELATED: FET-435 upgrade dependencies, use Node 12 for builds

### PR DESCRIPTION
**Pull request by no23reason**
Can be released as a patch version, it passes in all the repositories.

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by kandl — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/6/ : SUCCESS in 20s

**Pull request merged**
