### PR TITLE
BUGFIX: FET-942 Upgrade jest to fix sonar vulnerabilities

### PR DESCRIPTION
**Pull request by fiedlr**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-css-style-gate-PR41

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-gate/4/ : SUCCESS in 54s
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-fossa-scanning-zuul-el7/6/ : SUCCESS in 2m 26s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/12/ : SUCCESS in 55s

**Pull request merged**
