### PR TITLE
RELATED: ONE-4116 Use files directive

### PR DESCRIPTION
**Pull request by pbenes**
... and stop testing for old node

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by martinmosko — APPROVED** [review]

**Comment by martinmosko** [comment]
LGTM

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/2/ : SUCCESS in 23s

**Pull request merged**
