### PR TITLE
RELATED: SPACE-2092 Update license

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded (check pipeline).

**Review by NestorEncinas — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result
 - No issue found. Congratulations!

More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-css-style-gate-PR44

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by ghost** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-sonarqube-scan-zuul-gate/7/ : SUCCESS in 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-fossa-scanning-zuul-el7/9/ : SUCCESS in 3m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-css-style-merge-compliance-check/15/ : SUCCESS in 18s

**Pull request merged**
